import Head from 'next/head'
import { StaticImageData } from 'next/image'
import React from 'react'
import Navbar from './Navbar'

interface AppProps {
    img: StaticImageData,
    title: string
}

interface LayoutProps {
    children: JSX.Element
}

const appData = [
    {

    }
]

const Layout = ( {children}:LayoutProps ) => {


  return (
    <>  
        <Head>
            <title>Frag-Z</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Root */}
        <div className="border">
            {/* App Row */}
            <div className="border h-fit w-42 absolute top-3 left-3">

            </div>
            {/* Page container */}
            <div className="border">
                {/* Page/Children */}
                {children}
            </div>
            {/* Navbar */}
            <Navbar/>
        </div>
    </>
  )
}

export default Layout