import Head from 'next/head'
import Image, { StaticImageData } from 'next/image'
import React from 'react'
import Navbar from './Navbar'
import fragz from '../public/appIcons/fragz.png'
import computer from '../public/appIcons/computer.png'
import folder from '../public/appIcons/folder.png'
import bin from '../public/appIcons/bin.png'
import { useRouter } from 'next/router'

interface AppProps {
    img: StaticImageData,
    title: string
}

interface LayoutProps {
    children: JSX.Element
}

const appData = [
    {
        img: computer,
        title: 'Computer'
    },
    {
        img: folder,
        title: 'User Files'
    },
    {
        img: fragz,
        title: 'FRAG-Z'
    },
    {
        img: bin,
        title: 'Recycle Bin'
    },
]

const Layout = ( {children}:LayoutProps ) => {
  const router = useRouter()

  const Minimize = () => {

    return (
        <span className='tab-button'>
            <span className='w-5/6 h-0 border absolute bottom-1 mx-auto border-black'/>
        </span>
    )
  }

  const Maximize = () => {

    return (
        <span className='tab-button'>
            <span className='w-5/6 h-5/6 border border-black border-t-4'/>
        </span>
    )
  }

  const Close = () => {

    return (
        <span className='tab-button'>
            <span className='text-lg font-semibold mr-[2px]'>X</span>
        </span>
    )
  }

  const App = ( { img, title }: AppProps ) => {
    return (
        <div className='flex flex-col my-3'>
            <span className="w-16 h-16 overflow-hidden mb-2">
                <Image className='object-fill' src={img} alt='img'/>
            </span>
            <h1 className='font-windows text-white text-center'>{title}</h1>
        </div>
    )
  }

  return (
    <>  
        <Head>
            <title>Frag-Z</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Root */}
        <div className="root border">
            {/* App Row - Lowest*/}
            <div className="flex flex-col items-center h-0 overflow-hidden lg:h-fit lg:w-42 absolute top-3 left-3 -z-10">
            {
                appData.map((val,i) => (
                    <App key={i} img={val.img} title={val.title} />
                ))
            }
            </div>
            {/* Page container - Highest*/}
            <div className="border lg:border-4 page-container">
                {/* Top tab */}
                <div className='w-full min-h-fit bg-[#C5C5C5] pt-[2px] pb-1'>
                    <div className="page-container-tab">
                        {/* Window info */}
                        <div className="w-full h-full flex flex-row items-center justify-start">
                            <Image className='h-7 w-7 mx-2' src={fragz} alt='logo'/>
                            <h1 className="font-windows text-white"> FRAG-Z &#8226; {(router.route ==='/') ? 'HOME' : router.route.toUpperCase().replace(/[^0-9a-z]/gi, '')}</h1>
                        </div>
                        {/* Tab button group */}
                        <div className="w-1/2 h-full flex flex-row items-center justify-end">
                            <Minimize/>
                            <Maximize/>
                            <Close/>
                        </div>
                    </div>
                </div>
                {/* Page/Children */}
                <div className='h-full border border-black border-l-2 border-t-2 border-b-slate-200 w-full overflow-y-scroll no-scrollbar'>
                    {children}
                </div>
            </div>
            {/* Navbar - Middle*/}
            <Navbar/>
        </div>
    </>
  )
}

export default Layout