import Head  from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'
import gif   from '../public/appIcons/skull.gif'
import { BiArrowBack } from 'react-icons/bi'

export default function Error() {


  return (
    <>
      <Head>
        <title>Frag-Z &#8226; Error</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full flex flex-col items-center justify-center">
            <div className="flex flex-col items-center">
              <span className='h-32 w-32 flex items-center justify-center'>
                <Image className='mx-auto' src={gif} alt='skull'/>
              </span>
              <h1 className="text-6xl text-white font-arash">THIS PAGE DOES NOT EXIST</h1>
                <Link className="text-6xl text-white font-arash" href={'/'}><BiArrowBack/></Link>
            </div>
      </main>
    </>
  )
}