import Head from 'next/head'
import Image, { StaticImageData } from 'next/image'
import React from 'react'
import logo from '../public/appIcons/fragz-logo.png'

export default function Development() {
  const [toggle,setToggle] = React.useState(false)

  return (
    <>
      <Head>
        <title>Frag-Z &#8226; Development </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full flex flex-col items-center justify-center">
        dev
      </main>
    </>
  )
}