import Head from 'next/head'
import React from 'react'


export default function Home() {
  const [toggle,setToggle] = React.useState(false)

  return (
    <>
      <Head>
        <title>Frag-Z &#8226; Wiki </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full flex flex-col items-center justify-center">
        wiki
      </main>
    </>
  )
}